# Autogenerated wrapper script for OpenLSTO_jll for x86_64-unknown-freebsd-cxx11
export m2do_3d_lsm, m2do_fea, m2do_lsm

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("OpenLSTO")
JLLWrappers.@declare_library_product(m2do_3d_lsm, "m2do_3d_lsm.so")
JLLWrappers.@declare_library_product(m2do_fea, "m2do_fea.so")
JLLWrappers.@declare_library_product(m2do_lsm, "m2do_lsm.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        m2do_3d_lsm,
        "lib/m2do_3d_lsm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        m2do_fea,
        "lib/m2do_fea.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        m2do_lsm,
        "lib/m2do_lsm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
